### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'max_steps'

### ISSUE THREAD

**Issue by YongzhengCui** [ggeorgak11/UPEN#1]
Hi,

I have a problem, when I run the command `python store_episodes_parallel.py --gpu_capacity 1 --scenes_list HxpKQynjfin --episodes_save_dir /home/ros/cyz/UPEN/my_models/ --root_path /home/ros/cyz/habitat-lab --episode_len 10
` an error like below occurs.

options:
split train
grid_dim 768
crop_size 160
cell_size 0.05
turn_angle 30
forward_step_size 0.25
n_spatial_classes 3
img_size 256
max_num_episodes 2500
episode_len 10
truncate_ep True
occupancy_height_thresh -1.0
scenes_list ['HxpKQynjfin']
root_path /home/ros/cyz/habitat-lab
episodes_path habitat-api/data/datasets/objectnav/mp3d/
ep_set v1
episodes_root 
scenes_dir habitat-api/data/scene_datasets/
episodes_save_dir /home/ros/cyz/UPEN/my_models/
gpu_capacity 1
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ros/anaconda3/envs/UPEN/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ros/anaconda3/envs/UPEN/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/ros/cyz/UPEN/store_episodes_parallel.py", line 67, in store_episodes
    data = HabitatDataScene(options, config_file, scene_id=scene_id, existing_episode_list=existing_episode_list)
  File "/home/ros/cyz/UPEN/datasets/dataloader.py", line 87, in __init__
    cfg.ENVIRONMENT.MAX_EPISODE_STEPS = options.max_steps
AttributeError: 'Namespace' object has no attribute 'max_steps'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "store_episodes_parallel.py", line 153, in <module>
    pool.starmap(store_episodes, args)
  File "/home/ros/anaconda3/envs/UPEN/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/ros/anaconda3/envs/UPEN/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AttributeError: 'Namespace' object has no attribute 'max_steps'

**Comment by ggeorgak11** [comment]
I pushed a fix. Please try again.

**Comment by YongzhengCui** [comment]
Thanks for your reply, the problem is solved. However, there is a problem when I try to generate the training data, the log shows "0", no data is generated under the specified directory.
The command I run is:

python store_episodes_parallel.py --gpu_capacity 1 --scenes_list HxpKQynjfin --episodes_save_dir /my_model --root_path /home/ros/cyz/habitat-lab --episode_len 10

The corresponding log output is:

OpenGL version: 4.6.0 NVIDIA 440.33.01
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_KHR_debug
Using driver workarounds:
    no-forward-compatible-core-context
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
I0424 21:41:57.030951 12079 ResourceManager.cpp:234] ResourceManager::loadStage : Not loading semantic mesh
I0424 21:41:57.030966 12079 ResourceManager.cpp:262] ResourceManager::loadStage : start load render asset /home/ros/cyz/habitat-labhabitat-api/data/scene_datasets/mp3d/HxpKQynjfin/HxpKQynjfin.glb.
I0424 21:41:57.030969 12079 ResourceManager.cpp:569] ResourceManager::loadStageInternal : Attempting to load stage /home/ros/cyz/habitat-labhabitat-api/data/scene_datasets/mp3d/HxpKQynjfin/HxpKQynjfin.glb 
I0424 21:41:57.030984 12079 ResourceManager.cpp:1119] Importing Basis files as BC7 for HxpKQynjfin.glb
W0424 21:41:57.532372 12079 Simulator.cpp:248] :
---
 The active scene does not contain semantic annotations. 
---
I0424 21:41:57.548833 12079 simulator.py:213] Loaded navmesh /home/ros/cyz/habitat-labhabitat-api/data/scene_datasets/mp3d/HxpKQynjfin/HxpKQynjfin.navmesh
0
Now the pool is closed and no longer available


Looking forward to hearing from you, thank you very much.

**Comment by ggeorgak11** [comment]
This is looks like a path issue. The path that you posted:
I0424 21:41:57.548833 12079 simulator.py:213] Loaded navmesh /home/ros/cyz/habitat-labhabitat-api/data/scene_datasets/mp3d/HxpKQynjfin/HxpKQynjfin.navmesh
needs to be fixed.

**Comment by BoLeiChen** [comment]
Hi, I am also plagued by this problem. The path to my data is：/home/cbl/habitat-lab/habitat-api/data/scene_datasets/mp3d/HxpKQynjfin/HxpKQynjfin.navmesh,  but also unable to generate data.

**Comment by ggeorgak11** [comment]
Did you confirm that is the right path to the glb and navmesh files? Probably you don't need both habitat-lab and habitat-api in the path.

**Comment by BoLeiChen** [comment]
Yes, I'm sure the glb and navmesh files can be found in the corresponding directory.

**Comment by huangzizhen** [comment]
> Yes, I'm sure the glb and navmesh files can be found in the corresponding directory.

@BoLeiChen  have you solve this problem,I meet the same

**Comment by huangzizhen** [comment]
> 
 @Cyz981126 have you solve this problem,I meet the same.thank you very much.
